const LanguageReplacement =
{
    LANGUAGES: {
        English: "English",
        Ukraine: "Ukraine",
    },
    VALUES: {
        English: { 
            "btn-online": "Online",
            "btn-local": "Local Game",
            "btn-bot": "Play with Bot",
            "btn-settings": "Settings",
            "auth": "To continue, log in with Google:",
            "loading": "Loading...",
            "connecting": "Connecting to the server..",
            "successful-connecting": "Successful connection to the server!",
            "btn-back": "Back",
            "ready": "Ready",
            "not-ready": "Not ready",
            "player-name": "Player",
            "attention": "Attention..",
            "fire": "Fire!",
            "reaction": "SHOT: RMB | CTRL | SPACE",
            "reaction-local": "SHOT: LEFT/RIGHT CTRL/SHIFT",
            "chat": "Waiting for both players to be ready..",
            "chat-input-offline": "Offline messaging is disabled.",
            "chat-input-online": "Send message.. [ENTER]",
            "rooms-count": "Rooms: ",
            "rooms-online": "Online: ",
            "change-nickname": "Change nickname",
            "room-name": "Room name",
            "room-pass": "Room password",
            "create-room": "Create room",
            "join-room": "Join room",
            "chat-menu-say-hi": "Welcome to the global chat",
            "chat-room-say-hi": "Welcome to the room %ROOM_NAME%. Password:",
            "shot-earlier": "shot earlier!",
            "both-plus-to-the-score": "Come on! We have a draw!",
            "fight-is-ended-draw": "Draw. The fight ended with a score",
            "wins-this-match": "wins this match with a score",
            "you-win": "You win!",
            "you-lose": "You lose.",
            "shot-ahead-of-time": "shot ahead of time! Reset ready.",
            "total-score": "Total score",
            "player-connected-to-room": "Player %PLAYER_NAME% has connected to the room",
            "player-disconnected-from-room": "Player %PLAYER_NAME% has disconnected from the room",
            "win-because-enemy-left": "The enemy was left the room.",
            "settings-language": "Language",
            "settings-volume": "Volume",
            "error-NotConnectedToServer": "You are not connected to the server!",
            "error-ServerNotWorking": "The server is down. Connection error!",
            "error-UserBanned": "You were disconnected from the server by reason [BAN].",
            "error-NotAuthorized": "You are not logged into your account. Action is impossible!",
            "error-PlayerInTheRoom": "You are in the playroom!",
            "error-RoomLength": "Incorrect room name! The string length must be between 3 and 25 characters.",
            "error-RoomNotFound": "The selected playroom was not found!",
            "error-RoomIsFull": "Room is full!",
            "error-RoomAlreadyExists": "Such a room already exists!",
            "error-IncorrectRoomName": "Incorrect room name!",
            "error-IncorrectRoomPass": "Invalid room password entered!",
            "error-IncorrectMessage": "Error sending message! The string length must be between 3 and 120 characters.",
            "error-WaitOpponent": "Wait for your opponent to connect to the room.",
            "error-LocalGameOnlyForPc": "Local game available only for PC."
        },
        Ukraine: { 
            "btn-online": "Онлайн гра",
            "btn-local": "Локальна гра",
            "btn-bot": "Грати проти бота",
            "btn-settings": "Налаштування",
            "auth": "Щоб продовжити, авторизуйтесь через Google:",
            "loading": "Завантаження..",
            "connecting": "Підключення до сервера..",
            "successful-connecting": "Успішне підключення до сервера!",
            "btn-back": "Назад",
            "ready": "Готовий",
            "not-ready": "Не готовий",
            "attention": "Увага..",
            "fire": "Вогонь!",
            "player-name": "Гравець",
            "reaction": "ПОСТРІЛ: ПКМ | CTRL | ПРОБІЛ",
            "reaction-local": "ПОСТРІЛ: LEFT/RIGHT CTRL/SHIFT",
            "chat": "Очікування готовності обох гравців..",
            "chat-input-offline": "Відправлення повідомлень в offline відключено.",
            "chat-input-online": "Надіслати повідомлення.. [ENTER]",
            "rooms-count": "Кімнат: ",
            "rooms-online": "Онлайн: ",
            "change-nickname": "Змінити нікнейм",
            "room-name": "Iм'я кімнати",
            "room-pass": "Пароль кімнати",
            "create-room": "Створити кімнату",
            "join-room": "Приєднатися",
            "chat-menu-say-hi": "Ласкаво просимо в глобальний чат",
            "chat-room-say-hi": "Ласкаво просимо в кімнату %ROOM_NAME%. Пароль:",
            "shot-earlier": "вистрілив раніше!",
            "both-plus-to-the-score": "Ого! У нас нічия!",
            "fight-is-ended-draw": "Нічия. Бій завершився з рахунком",
            "wins-this-match": "перемагає в цьому поєдинку з рахунком",
            "you-win": "Ти переміг!",
            "you-lose": "Ти програв.",
            "shot-ahead-of-time": "вистрілив завчасно! Скидання готовності.",
            "total-score": "Загальний рахунок",
            "player-connected-to-room": "Гравець %PLAYER_NAME% підключився до кімнати",
            "player-disconnected-from-room": "Гравець %PLAYER_NAME% відключився від кімнати",
            "win-because-enemy-left": "Противник вийшов з кімнати.",
            "settings-language": "Мова",
            "settings-volume": "Звук",
            "error-NotConnectedToServer": "Ви не підключені до сервера!",
            "error-ServerNotWorking": "Сервер відключений. Помилка з'єднання!",
            "error-UserBanned": "Ви були примусово відключені від сервера через [BAN].",
            "error-NotAuthorized": "Ви не ввійшли до свого облікового запису. Дія неможлива!",
            "error-PlayerInTheRoom": "Ви вже перебуваєте в ігровій кімнаті!",
            "error-RoomLength": "Некоректна назва кімнати! Довжина рядка повинна бути від 3-х до 25-ти символів.",
            "error-RoomNotFound": "Обрана ігрова кімната не знайдена!",
            "error-RoomIsFull": "У цій кімнаті немає вільних місць!",
            "error-RoomAlreadyExists": "Така кімната вже існує!",
            "error-IncorrectRoomName": "Некоректна назва кімнати!",
            "error-IncorrectRoomPass": "Введено недійсний пароль кімнати!",
            "error-IncorrectMessage": "Помилка відправки повідомлення! Довжина рядка повинна бути від 1 до 120 символів.",
            "error-WaitOpponent": "Зачекайте поки Ваш опонент підключиться до кімнати.",
            "error-LocalGameOnlyForPc": "Локальная гра доступна тільки для комп'ютерів!"
        }
    }
};